### ISSUE TITLE
🐞 [Bug]: Unable to connect to an account

### ISSUE THREAD

**Issue by a1mery** [pnp/vscode-viva#31] opened 2023-05-03 13:53 UTC
## 📝 Describe the bug

Unable to connect to an account.

## 👣 Steps To Reproduce

Maybe I'm missing something but I'm not able to connect to my tenant from the account section:
1. Install the Viva Connections Toolkit
2. Access the toolkit home page
3. The account section doesn't display a button to connect to an account

## 📜 Expected behavior

I should be able to connect to my M365 tenant from the account section.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/7100077/235935596-43e038ef-bebd-4e7b-ac67-d537c2bb0c30.png)

## 💻 Desktop (please complete the following information):

- Viva Connections Toolkit v0.5.1
- Visual Studio Code 1.77.3

**Comment by Adam-it** [comment] 2023-05-03 22:42
@a1mery sorry to hear you are having trouble with the extension. The extension is still in the early stage so we probably did not catch all the edge cases so first of all I would like to thank you for opening an issue and sharing your feedback 👍
Could you provide the additional details:
- Are you (by any chance) working on a Mac? 
- Did you use CLI for M365 before on the same device?

could you try those steps to trouble shoot the problem (the basic idea is to use commands instead of clicking the UI):
please do the following:
1. open VS Code and wait for the extension to start and for the error to reproduce
2. hit F1 (command pallete)
3. type `viva Connections Toolkit: Sign out from M365`
4. then do `viva Connections Toolkit: Sign in from M365` and follow the wizard steps
5. after that let's see if the UI will show your account. If so please log out using the UI and retry login

**Comment by a1mery** [comment] 2023-05-04 08:41
I tried this: `viva Connections Toolkit: Sign out from M365` and it worked, I could sign in to my account using the UI :)
![image](https://user-images.githubusercontent.com/7100077/236153589-d1c70a0e-ea34-4a54-b3a9-153b2dffc120.png)

If it helps:

- I am not working on a Mac
- I've already used CLI for M365 on this device

Thank you @Adam-it for your help and your work on this great extension !

**Comment by Adam-it** [comment] 2023-05-04 10:11
Awesome to hear you were able to resolve the issue 👍. You rock 🤩.
It's really hard to say what might had happened at this time 🤔 I tried to debug the issue but since I was not able to reproduce it I have no other fix besides the advice I gave you for now.
Since it's working currently let's close it for now 👍
Once again thanks for your feedback and tests

**Closed by Adam-it** 2023-05-04 10:11 UTC
Labels: 🐞 bug, 👨‍💻work in progress
